"""Shell / dummy provider.

Always available. Echoes the prompt back and, when asked to write files,
emits a short stub. This keeps the harness functional without any
external coding agent installed - useful for smoke tests, CI, and dry
runs.
"""

from __future__ import annotations

import json
import sys
import traceback
from pathlib import Path
from typing import Any, Dict

from .base import AgentProvider, AgentRequest, AgentResponse, estimate_tokens


class ShellProvider(AgentProvider):
    type_name = "shell"

    def available(self) -> bool:
        return True

    def invoke(self, req: AgentRequest) -> AgentResponse:
        try:
            files_written: list[str] = []
            preview = (req.prompt or "").strip().splitlines()[:3]
            text_lines = [
                f"[shell-provider] agent={req.agent}",
                f"[shell-provider] dry_run={req.dry_run}",
                "[shell-provider] prompt preview:",
                *[f"  {l}" for l in preview],
            ]

            if req.dry_run:
                usage = estimate_tokens(req.prompt, "\n".join(text_lines))
                usage["source"] = "shell-estimate"
                return AgentResponse(
                    ok=True,
                    text="\n".join(text_lines),
                    raw={"dry_run": True},
                    usage=usage,
                )

            workdir = Path(req.workdir) if req.workdir else Path.cwd()
            stub_dir = workdir / ".clk" / "runs" / "shell-stubs"
            try:
                stub_dir.mkdir(parents=True, exist_ok=True)
                stub = stub_dir / f"{req.agent}.md"
                stub.write_text(
                    f"# {req.agent} stub output\n\n"
                    f"Generated by ShellProvider. Replace with a real provider for actual work.\n\n"
                    f"## Prompt\n\n```\n{req.prompt}\n```\n",
                    encoding="utf-8",
                )
                files_written.append(str(stub.relative_to(workdir)))
            except Exception as exc:
                print(f"[providers.shell.invoke] failed to write stub: {exc}", file=sys.stderr)
                traceback.print_exc()

            text_lines.append(f"[shell-provider] wrote {len(files_written)} file(s)")
            response_text = "\n".join(text_lines)
            usage = estimate_tokens(req.prompt, response_text)
            usage["source"] = "shell-estimate"
            return AgentResponse(
                ok=True,
                text=response_text,
                files_written=files_written,
                raw={"agent": req.agent, "kind": "shell-stub"},
                usage=usage,
            )
        except Exception as exc:
            print(f"[providers.shell.invoke] failed: {exc}", file=sys.stderr)
            traceback.print_exc()
            return AgentResponse(ok=False, error=str(exc))
