"""Git utilities for CLK.

CLK uses git as both a versioning system and a memory store: every
successful agent or workflow milestone is committed with a structured
message so that future iterations can mine the log for context.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import traceback
from pathlib import Path
from typing import Iterable, List, Optional

from .utils.logging_utils import log, log_exception


def have_git() -> bool:
    return shutil.which("git") is not None


def is_repo(root: Path) -> bool:
    if not have_git():
        return False
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )
        return r.returncode == 0 and r.stdout.strip() == "true"
    except Exception as exc:
        log_exception("git_ops.is_repo", exc)
        return False


def init_repo(root: Path) -> bool:
    if not have_git():
        log("git not found on PATH; skipping git init", level="WARN")
        return False
    if is_repo(root):
        return True
    try:
        subprocess.run(
            ["git", "init", "-q"], cwd=root, check=True, capture_output=True, text=True
        )
        # Set a safe default branch if needed.
        try:
            subprocess.run(
                ["git", "symbolic-ref", "HEAD", "refs/heads/main"],
                cwd=root,
                check=False,
                capture_output=True,
            )
        except Exception as exc:
            log_exception("git_ops.init_repo.symref", exc)
        # Configure local identity if missing so commits don't fail on
        # systems without a global git config.
        _ensure_local_identity(root)
        return True
    except Exception as exc:
        log_exception("git_ops.init_repo", exc)
        return False


def _ensure_local_identity(root: Path) -> None:
    try:
        name = subprocess.run(
            ["git", "config", "user.name"], cwd=root, capture_output=True, text=True
        )
        if not name.stdout.strip():
            subprocess.run(
                ["git", "config", "user.name", "CLK Harness"],
                cwd=root, check=False, capture_output=True, text=True,
            )
        email = subprocess.run(
            ["git", "config", "user.email"], cwd=root, capture_output=True, text=True
        )
        if not email.stdout.strip():
            subprocess.run(
                ["git", "config", "user.email", "clk@local.invalid"],
                cwd=root, check=False, capture_output=True, text=True,
            )
    except Exception as exc:
        log_exception("git_ops._ensure_local_identity", exc)


def status_porcelain(root: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return r.stdout
    except Exception as exc:
        log_exception("git_ops.status_porcelain", exc)
        return ""


def add(root: Path, paths: Iterable[str]) -> bool:
    paths = list(paths)
    if not paths:
        return True
    try:
        subprocess.run(
            ["git", "add", "--", *paths], cwd=root, check=True, capture_output=True, text=True
        )
        return True
    except Exception as exc:
        log_exception("git_ops.add", exc)
        return False


def add_all(root: Path) -> bool:
    try:
        subprocess.run(
            ["git", "add", "-A"], cwd=root, check=True, capture_output=True, text=True
        )
        return True
    except Exception as exc:
        log_exception("git_ops.add_all", exc)
        return False


def has_changes(root: Path) -> bool:
    return bool(status_porcelain(root).strip())


def commit(
    root: Path,
    *,
    agent: str,
    objective: str,
    files_changed: Optional[List[str]] = None,
    validation: Optional[str] = None,
    next_step: Optional[str] = None,
    body_extra: Optional[str] = None,
    allow_empty: bool = False,
) -> bool:
    """Create a structured commit. Returns True on success."""
    if not is_repo(root):
        log("commit skipped; not a git repo", level="WARN")
        return False

    title = f"[{agent}] {objective.strip()}"[:120]
    body_lines: List[str] = []
    if files_changed:
        body_lines.append("Files changed:")
        for f in files_changed:
            body_lines.append(f"  - {f}")
    if validation:
        body_lines.append("")
        body_lines.append(f"Validation: {validation}")
    if next_step:
        body_lines.append(f"Next step: {next_step}")
    if body_extra:
        body_lines.append("")
        body_lines.append(body_extra)
    body_lines.append("")
    body_lines.append("Generated by CLK (Cognitive Loop Kernel)")
    msg = title + "\n\n" + "\n".join(body_lines)

    cmd = ["git", "commit", "-m", msg]
    if allow_empty:
        cmd.insert(2, "--allow-empty")
    try:
        subprocess.run(cmd, cwd=root, check=True, capture_output=True, text=True)
        return True
    except subprocess.CalledProcessError as exc:
        log(f"commit failed: rc={exc.returncode} stderr={exc.stderr.strip()}", level="WARN")
        return False
    except Exception as exc:
        log_exception("git_ops.commit", exc)
        return False


def head_sha(root: Path) -> Optional[str]:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return r.stdout.strip()
    except Exception as exc:
        log_exception("git_ops.head_sha", exc)
        return None


def revert_to(root: Path, sha: str) -> bool:
    try:
        subprocess.run(
            ["git", "reset", "--hard", "--quiet", sha],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return True
    except Exception as exc:
        log_exception("git_ops.revert_to", exc)
        return False


def changed_files_since(root: Path, sha: str) -> List[str]:
    try:
        r = subprocess.run(
            ["git", "diff", "--name-only", sha, "HEAD"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return [l for l in r.stdout.splitlines() if l.strip()]
    except Exception as exc:
        log_exception("git_ops.changed_files_since", exc)
        return []
