"""Git utilities for CLK.

CLK uses git as both a versioning system and a memory store: every
successful agent or workflow milestone is committed with a structured
message so that future iterations can mine the log for context.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Iterable, List, Optional

from .utils.logging_utils import log, log_exception


def have_git() -> bool:
    return shutil.which("git") is not None


def is_repo(root: Path) -> bool:
    if not have_git():
        return False
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )
        return r.returncode == 0 and r.stdout.strip() == "true"
    except Exception as exc:
        log_exception("git_ops.is_repo", exc)
        return False


def init_repo(root: Path) -> bool:
    if not have_git():
        log("git not found on PATH; skipping git init", level="WARN")
        return False
    if is_repo(root):
        return True
    try:
        subprocess.run(
            ["git", "init", "-q"], cwd=root, check=True, capture_output=True, text=True
        )
        # Set a safe default branch if needed.
        try:
            subprocess.run(
                ["git", "symbolic-ref", "HEAD", "refs/heads/main"],
                cwd=root,
                check=False,
                capture_output=True,
            )
        except Exception as exc:
            log_exception("git_ops.init_repo.symref", exc)
        # Configure local identity if missing so commits don't fail on
        # systems without a global git config.
        _ensure_local_identity(root)
        return True
    except Exception as exc:
        log_exception("git_ops.init_repo", exc)
        return False


def _ensure_local_identity(root: Path) -> None:
    try:
        name = subprocess.run(
            ["git", "config", "user.name"], cwd=root, capture_output=True, text=True
        )
        if not name.stdout.strip():
            subprocess.run(
                ["git", "config", "user.name", "CLK Harness"],
                cwd=root, check=False, capture_output=True, text=True,
            )
        email = subprocess.run(
            ["git", "config", "user.email"], cwd=root, capture_output=True, text=True
        )
        if not email.stdout.strip():
            subprocess.run(
                ["git", "config", "user.email", "clk@local.invalid"],
                cwd=root, check=False, capture_output=True, text=True,
            )
    except Exception as exc:
        log_exception("git_ops._ensure_local_identity", exc)


def status_porcelain(root: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return r.stdout
    except Exception as exc:
        log_exception("git_ops.status_porcelain", exc)
        return ""


def add(root: Path, paths: Iterable[str]) -> bool:
    paths = list(paths)
    if not paths:
        return True
    try:
        subprocess.run(
            ["git", "add", "--", *paths], cwd=root, check=True, capture_output=True, text=True
        )
        return True
    except Exception as exc:
        log_exception("git_ops.add", exc)
        return False


def add_all(root: Path) -> bool:
    try:
        subprocess.run(
            ["git", "add", "-A"], cwd=root, check=True, capture_output=True, text=True
        )
        return True
    except Exception as exc:
        log_exception("git_ops.add_all", exc)
        return False


def has_changes(root: Path) -> bool:
    return bool(status_porcelain(root).strip())


def commit(
    root: Path,
    *,
    agent: str,
    objective: str,
    files_changed: Optional[List[str]] = None,
    validation: Optional[str] = None,
    next_step: Optional[str] = None,
    body_extra: Optional[str] = None,
    allow_empty: bool = False,
) -> bool:
    """Create a structured commit. Returns True on success."""
    if not is_repo(root):
        log("commit skipped; not a git repo", level="WARN")
        return False

    title = f"[{agent}] {objective.strip()}"[:120]
    body_lines: List[str] = []
    if files_changed:
        body_lines.append("Files changed:")
        for f in files_changed:
            body_lines.append(f"  - {f}")
    if validation:
        body_lines.append("")
        body_lines.append(f"Validation: {validation}")
    if next_step:
        body_lines.append(f"Next step: {next_step}")
    if body_extra:
        body_lines.append("")
        body_lines.append(body_extra)
    body_lines.append("")
    body_lines.append("Generated by CLK (Cognitive Loop Kernel)")
    msg = title + "\n\n" + "\n".join(body_lines)

    cmd = ["git", "commit", "-m", msg]
    if allow_empty:
        cmd.insert(2, "--allow-empty")
    try:
        subprocess.run(cmd, cwd=root, check=True, capture_output=True, text=True)
        return True
    except subprocess.CalledProcessError as exc:
        log(f"commit failed: rc={exc.returncode} stderr={exc.stderr.strip()}", level="WARN")
        return False
    except Exception as exc:
        log_exception("git_ops.commit", exc)
        return False


def commit_trace(
    root: Path,
    *,
    kind: str,
    summary: str,
    meta: Optional[dict] = None,
    stage_all: bool = True,
    allow_empty: bool = True,
) -> bool:
    """Write a structured *execution-trace* commit.

    Used at mission boundaries (charter / plan / phase-start /
    phase-gate:<verdict> / cycle:<n>) and per ACTION batch so the git log
    itself becomes the audit trail of an autonomous run. The title is
    ``[clk:<kind>] <summary>`` — a machine-greppable marker — and the body
    carries the ``meta`` key/values (agent, phase, files, verdicts, tokens).

    ``allow_empty`` defaults True so a boundary marker lands even when the
    cycle produced no file change, keeping the trace gap-free. Returns True
    on a successful commit (or when there was genuinely nothing to do and
    ``allow_empty`` is False).
    """
    if not is_repo(root):
        return False
    if stage_all:
        add_all(root)
    body_lines: List[str] = []
    for key, value in (meta or {}).items():
        if value is None:
            continue
        if isinstance(value, (list, tuple)):
            value = ", ".join(str(v) for v in value)
        body_lines.append(f"{key}: {value}")
    body_extra = "\n".join(body_lines) if body_lines else None
    return commit(
        root,
        agent=f"clk:{kind}",
        objective=summary,
        body_extra=body_extra,
        allow_empty=allow_empty,
    )


def head_sha(root: Path) -> Optional[str]:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return r.stdout.strip()
    except Exception as exc:
        log_exception("git_ops.head_sha", exc)
        return None


def has_remote(root: Path, name: str = "origin") -> bool:
    """Return True if the repo has a remote with the given name."""
    try:
        r = subprocess.run(
            ["git", "remote", "get-url", name],
            cwd=root, capture_output=True, text=True, check=False,
        )
        return r.returncode == 0
    except Exception as exc:
        log_exception("git_ops.has_remote", exc)
        return False


def commits_ahead(root: Path, remote: str = "origin") -> int:
    """How many local commits are not yet on ``remote``'s tracked branch.

    Returns 0 on any error (no remote, no upstream, network failure)
    so the caller can use this directly in a UI count.
    """
    try:
        # First check there is an upstream — without it `git rev-list`
        # below would fail noisily.
        r = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}"],
            cwd=root, capture_output=True, text=True, check=False,
        )
        if r.returncode != 0:
            return 0
        r = subprocess.run(
            ["git", "rev-list", "--count", "@{u}..HEAD"],
            cwd=root, capture_output=True, text=True, check=False,
        )
        if r.returncode != 0:
            return 0
        return int(r.stdout.strip() or "0")
    except Exception as exc:
        log_exception("git_ops.commits_ahead", exc)
        return 0


def push(root: Path, remote: str = "origin", branch: Optional[str] = None) -> bool:
    """Best-effort push to ``remote``. Returns True on success.

    Used by the harness when ``CLK_GITHUB_PUSH_ON_COMMIT=true`` is set
    — failures are logged but never raise. The harness keeps working
    locally even when the network is down.
    """
    if not is_repo(root) or not has_remote(root, remote):
        return False
    args = ["git", "push", remote]
    if branch:
        args.append(branch)
    else:
        args.append("HEAD")
    try:
        r = subprocess.run(args, cwd=root, capture_output=True, text=True, check=False)
        if r.returncode == 0:
            return True
        log(f"push failed: rc={r.returncode} stderr={r.stderr.strip()[:200]}", level="WARN")
        return False
    except Exception as exc:
        log_exception("git_ops.push", exc)
        return False


def revert_to(root: Path, sha: str) -> bool:
    try:
        subprocess.run(
            ["git", "reset", "--hard", "--quiet", sha],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return True
    except Exception as exc:
        log_exception("git_ops.revert_to", exc)
        return False


def changed_files_since(root: Path, sha: str) -> List[str]:
    try:
        r = subprocess.run(
            ["git", "diff", "--name-only", sha, "HEAD"],
            cwd=root, check=True, capture_output=True, text=True,
        )
        return [ln for ln in r.stdout.splitlines() if ln.strip()]
    except Exception as exc:
        log_exception("git_ops.changed_files_since", exc)
        return []


# History mining (read-only; powers the web UI Files tab) -------------------

_FIELD_SEP = "\x1f"
_RECORD_SEP = "\x1e"
_LOG_FORMAT = _FIELD_SEP.join(["%H", "%h", "%an", "%aI", "%s"])


def _filter_internal(path: str) -> bool:
    """True when ``path`` is a harness-internal file we hide from users."""
    top = path.split("/", 1)[0]
    return top in {".clk", ".git", "node_modules", "__pycache__"}


def log_entries(
    root: Path, *, path: Optional[str] = None, limit: int = 100,
    rev: Optional[str] = None,
) -> List[dict]:
    """Commit history newest-first, with per-commit file stats.

    When ``path`` is given, only commits touching that file are returned
    (renames followed). When ``rev`` is given, history starts at that
    commit. Harness-internal paths are dropped from the file stats;
    commits whose every change is internal are dropped entirely.
    """
    if not is_repo(root):
        return []
    args = [
        "git", "log", f"--max-count={int(limit)}",
        f"--pretty=format:{_RECORD_SEP}{_LOG_FORMAT}", "--numstat",
    ]
    if rev:
        args.append(rev)
    if path:
        args += ["--follow", "--", path]
    try:
        r = subprocess.run(args, cwd=root, check=True, capture_output=True, text=True)
    except Exception as exc:
        log_exception("git_ops.log_entries", exc)
        return []

    commits: List[dict] = []
    for record in r.stdout.split(_RECORD_SEP):
        record = record.strip("\n")
        if not record:
            continue
        head, _, stat_block = record.partition("\n")
        fields = head.split(_FIELD_SEP)
        if len(fields) != 5:
            continue
        sha, short, author, date, subject = fields
        files: List[dict] = []
        insertions = deletions = 0
        for line in stat_block.splitlines():
            parts = line.split("\t")
            if len(parts) != 3:
                continue
            ins, dels, fpath = parts
            # Rename lines look like "old => new" or "{a => b}/x".
            fpath = fpath.split(" => ")[-1].replace("}", "").replace("{", "")
            if _filter_internal(fpath):
                continue
            fi = 0 if ins == "-" else int(ins)
            fd = 0 if dels == "-" else int(dels)
            insertions += fi
            deletions += fd
            files.append({"path": fpath, "insertions": fi, "deletions": fd})
        if not files and stat_block.strip():
            continue  # commit only touched internal paths
        commits.append({
            "sha": sha,
            "short": short,
            "author": author,
            "date": date,
            "subject": subject,
            "insertions": insertions,
            "deletions": deletions,
            "files": files,
        })
    return commits


def commit_patch(root: Path, sha: str, *, max_bytes: int = 200_000) -> Optional[dict]:
    """Unified diff for one commit, truncated to ``max_bytes``.

    Harness-internal paths are excluded so the patch matches what the
    Files tab shows.
    """
    if not is_repo(root):
        return None
    excludes = [f":(exclude){d}" for d in (".clk", ".git", "node_modules", "__pycache__")]
    try:
        r = subprocess.run(
            ["git", "show", sha, "--patch", "--no-color",
             "--pretty=format:", "--", ".", *excludes],
            cwd=root, check=True, capture_output=True, text=True,
        )
    except Exception as exc:
        log_exception("git_ops.commit_patch", exc)
        return None
    patch = r.stdout.lstrip("\n")
    truncated = len(patch.encode("utf-8")) > max_bytes
    if truncated:
        patch = patch.encode("utf-8")[:max_bytes].decode("utf-8", errors="replace")
    return {"patch": patch, "truncated": truncated}


def snapshot_rollback(root: Path, stage_id: str) -> bool:
    """Preserve about-to-be-rolled-back work behind ``refs/clk/rollbacks/``.

    A hard reset makes the batch commits since the pre-stage SHA dangling;
    pointing a ref at HEAD first keeps them reachable so a user (or a
    future recovery pass) can recover the discarded work with git.
    """
    if not is_repo(root):
        return False
    sha = head_sha(root)
    if not sha:
        return False
    import re as _re
    import time as _time

    safe = _re.sub(r"[^A-Za-z0-9_-]+", "-", stage_id)[:40] or "stage"
    ref = f"refs/clk/rollbacks/{safe}-{int(_time.time())}"
    try:
        r = subprocess.run(
            ["git", "update-ref", ref, sha],
            cwd=root, capture_output=True, text=True, check=False,
        )
        if r.returncode == 0:
            log(f"rollback snapshot saved: {ref} -> {sha[:8]}")
            return True
        return False
    except Exception as exc:
        log_exception("git_ops.snapshot_rollback", exc)
        return False


def status_entries(root: Path) -> List[dict]:
    """Working-tree changes vs HEAD as ``{path, state}`` entries.

    States: ``new`` (untracked or added), ``modified``, ``deleted``,
    ``renamed``. Harness-internal paths are dropped to match the Files tab.
    """
    entries: List[dict] = []
    for line in status_porcelain(root).splitlines():
        if len(line) < 4:
            continue
        code, rest = line[:2], line[3:]
        # Renames look like "R  old -> new"; show the new path.
        path = rest.split(" -> ")[-1].strip().strip('"')
        if _filter_internal(path):
            continue
        if code == "??" or "A" in code:
            state = "new"
        elif "R" in code:
            state = "renamed"
        elif "D" in code:
            state = "deleted"
        else:
            state = "modified"
        entries.append({"path": path, "state": state})
    entries.sort(key=lambda e: e["path"])
    return entries


def working_tree_patch(root: Path, *, max_bytes: int = 200_000) -> Optional[dict]:
    """Unified diff of uncommitted changes vs HEAD (internal paths excluded).

    Untracked files don't appear in ``git diff``; callers should pair this
    with :func:`status_entries` to list them.
    """
    if not is_repo(root):
        return None
    excludes = [f":(exclude){d}" for d in (".clk", ".git", "node_modules", "__pycache__")]
    try:
        r = subprocess.run(
            ["git", "diff", "HEAD", "--no-color", "--", ".", *excludes],
            cwd=root, check=False, capture_output=True, text=True,
        )
        if r.returncode not in (0, 1):  # diff exits 1 with --exit-code semantics on some configs
            return None
    except Exception as exc:
        log_exception("git_ops.working_tree_patch", exc)
        return None
    patch = r.stdout
    truncated = len(patch.encode("utf-8")) > max_bytes
    if truncated:
        patch = patch.encode("utf-8")[:max_bytes].decode("utf-8", errors="replace")
    return {"patch": patch, "truncated": truncated}


def file_at(root: Path, sha: str, path: str) -> Optional[bytes]:
    """Raw bytes of ``path`` as of commit ``sha``, or None if absent."""
    if not is_repo(root):
        return None
    try:
        r = subprocess.run(
            ["git", "show", f"{sha}:{path}"],
            cwd=root, check=False, capture_output=True,
        )
        if r.returncode != 0:
            return None
        return r.stdout
    except Exception as exc:
        log_exception("git_ops.file_at", exc)
        return None
