"""Tests for the ``clk kickoff`` subcommand (clk_harness/kickoff.py).

Golden-file parity: the goldens under ``tests/golden/kickoff/`` were
generated by running the *original* kickoff.sh Python heredocs (the
CLK_* env → clk.config.json override block and the provider-activation
block) against snapshot base configs for the env matrices below.  The
ported :func:`apply_config_env_overrides` / :func:`activate_provider`
must produce byte-identical output for the same inputs.

The matrices are imported by the one-shot golden generator, so they are
the single source of truth for both sides of the comparison.  Do not
edit a case without regenerating its golden from the shell heredoc (or
consciously re-deriving it).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import time
from pathlib import Path

import pytest

from clk_harness import kickoff
from clk_harness.cli import build_parser
from clk_harness.kickoff import activate_provider, apply_config_env_overrides, _bool, _csv

GOLDEN = Path(__file__).resolve().parent / "golden" / "kickoff"


# ---------------------------------------------------------------------------
# Env-input matrices (shared with the golden generator)
# ---------------------------------------------------------------------------

CONFIG_CASES: dict = {
    "no_overrides": {},
    # Every recognised var with a distinctive valid value.
    "full_valid": {
        "CLK_ROBUSTNESS_AUTO_CONSENSUS": "always",
        "CLK_ROBUSTNESS_AUTO_REFINE": "careful_only",
        "CLK_ROBUSTNESS_MAX_QUALITY_RETRIES": "7",
        "CLK_ROBUSTNESS_MIN_RESPONSE_CHARS": "99",
        "CLK_ROBUSTNESS_REFINE_MAX_ROUNDS": "4",
        "CLK_ROBUSTNESS_REFINE_ACCEPT_THRESHOLD": "0.65",
        "CLK_ROBUSTNESS_QA_PARALLEL_JUDGES": "3",
        "CLK_ROBUSTNESS_MAX_QA_DEPTH": "2",
        "CLK_ROBUSTNESS_PLATEAU_WINDOW": "9",
        "CLK_ROBUSTNESS_PLATEAU_ACTION": "escalate_only",
        "CLK_ROBUSTNESS_DEBATE": "all",
        "CLK_ROBUSTNESS_DEBATE_LENSES": "correctness,performance",
        "CLK_ROBUSTNESS_DEBATE_MAX_ROUNDS": "5",
        "CLK_MISSION_MAX_PHASES": "8",
        "CLK_MISSION_MAX_ITERATIONS_PER_PHASE": "2",
        "CLK_MISSION_MAX_TOTAL_CYCLES": "33",
        "CLK_MISSION_PHASE_GATE": "false",
        "CLK_MISSION_REFINE_REQUIRED": "true",
        "CLK_MISSION_AUTO_CONSENSUS_ON_STALL": "false",
        "CLK_MISSION_CHARTER_FIRST": "false",
        "CLK_MISSION_COMMIT_TRACE": "true",
        "CLK_MISSION_COMMIT_GRANULARITY": "coarse",
        "CLK_MISSION_MIN_CYCLES_BEFORE_DONE": "2",
        "CLK_MISSION_TELEMETRY_STDOUT": "false",
        "CLK_MISSION_ON_BUDGET_EXHAUSTED": "fail",
        "CLK_MISSION_DEFAULT_PHASES": "discovery,engineering",
        "CLK_DONE_GATE_ENABLED": "true",
        "CLK_DONE_GATE_REQUIRE_TESTS_GREEN": "false",
        "CLK_DONE_GATE_REQUIRE_DELIVERABLES": "true",
        "CLK_DONE_GATE_MIN_DELIVERABLE_FILES": "3",
        "CLK_DONE_GATE_REQUIRE_QA_PASS": "false",
        "CLK_DONE_GATE_REQUIRE_RALPH_PASS": "false",
        "CLK_DONE_GATE_FORBID_TODO_MARKERS": "true",
        "CLK_DONE_GATE_MAX_FINISH_ATTEMPTS": "9",
        "CLK_NOOP_GUARD_ENABLED": "false",
        "CLK_NOOP_GUARD_MAX_REDISPATCH": "4",
        "CLK_NOOP_GUARD_PRODUCING_AGENTS": "engineer,ralph,builder",
        "CLK_NOOP_GUARD_TREAT_OUTPUTS_STAGE_AS_PRODUCING": "false",
        "CLK_DELIBERATION_ENABLED": "false",
        "CLK_DELIBERATION_ENCOURAGE_QUESTIONS": "false",
        "CLK_DELIBERATION_REQUIRE_OPEN_QUESTIONS_RESOLVED": "false",
        "CLK_DELIBERATION_SELF_REFLECT_PREAMBLE": "false",
        "CLK_DELIBERATION_MIN_DEBATE_ROUNDS": "2",
        "CLK_VALIDATION_AUTO_DERIVE": "false",
        "CLK_PROVIDER_TIMEOUT_S": "600",
        "CLK_PROVIDER_NO_OUTPUT_TIMEOUT_S": "120",
        "CLK_PROVIDER_RETRY_MAX_RETRIES": "3",
        "CLK_PROVIDER_RETRY_BACKOFF_S": "2.5",
        "CLK_PROVIDER_RETRY_STAGE_MAX_RETRIES": "4",
        "CLK_PROVIDER_RETRY_STAGE_BACKOFF_S": "12.75",
        "CLK_SUPERVISE_MAX_CYCLES": "50",
        "CLK_CONSENSUS_MAX_SAMPLES": "5",
        "CLK_CONSENSUS_MAX_PARALLEL": "2",
        "CLK_CASTING_MAX_DYNAMIC_ROLES": "6",
        "CLK_AUTO_COMMIT": "false",
        "CLK_VALIDATION_MAX_FILES_PER_BATCH": "10",
        "CLK_VALIDATION_WARN_FILES_PER_BATCH": "3",
        "CLK_META_PROMPT_DISPATCH": "off",
        "CLK_META_PROMPT_ROLE": "careful_only",
        "CLK_REVIEW_PER_STAGE": "true",
        "CLK_RECOVERY_MAX_PER_STAGE": "1",
    },
    # _bool truthy spellings: {"1","true","yes","y","on"} after strip+lower.
    "bool_truthy_variants": {
        "CLK_MISSION_PHASE_GATE": "Yes",
        "CLK_MISSION_CHARTER_FIRST": "1",
        "CLK_DONE_GATE_ENABLED": "ON",
        "CLK_AUTO_COMMIT": "  TRUE  ",
        "CLK_REVIEW_PER_STAGE": "y",
    },
    # Everything else (including garbage) is False — never an error.
    "bool_falsy_variants": {
        "CLK_MISSION_PHASE_GATE": "0",
        "CLK_DONE_GATE_ENABLED": "off",
        "CLK_NOOP_GUARD_ENABLED": "no",
        "CLK_DELIBERATION_ENABLED": "garbage",
        "CLK_AUTO_COMMIT": "False",
        "CLK_VALIDATION_AUTO_DERIVE": "n",
    },
    # _csv: split on commas, strip items, drop empties.
    "csv_edge_cases": {
        "CLK_ROBUSTNESS_DEBATE_LENSES": "  a , ,b ,,c  ",
        "CLK_MISSION_DEFAULT_PHASES": "solo",
        "CLK_NOOP_GUARD_PRODUCING_AGENTS": " , ,, ",
    },
    # Uncastable / empty values are skipped; the default survives.
    "invalid_and_empty_values": {
        "CLK_ROBUSTNESS_MAX_QUALITY_RETRIES": "abc",      # int() fails -> skipped
        "CLK_ROBUSTNESS_REFINE_ACCEPT_THRESHOLD": "x.y",  # float() fails -> skipped
        "CLK_PROVIDER_TIMEOUT_S": "",                     # empty -> skipped
        "CLK_SUPERVISE_MAX_CYCLES": "3.5",                # int("3.5") fails -> skipped
        "CLK_PROVIDER_RETRY_BACKOFF_S": "1.5",            # float ok
        "CLK_CONSENSUS_MAX_SAMPLES": "  7  ",             # int tolerates whitespace
        "CLK_UNRELATED_VAR": "ignored",                   # unknown var -> no effect
    },
}

# Raw user env for the provider-activation block. The wrapper defaults
# (CLK_AUTH_MODE=cli, ollama endpoint/model, blank openwebui/pi vars)
# are applied by activate_provider itself, mirroring the `VAR=${VAR:-def}`
# prefixes kickoff.sh put on the heredoc invocation.
PROVIDER_CASES: dict = {
    "shell_default": {"CLK_PROVIDER": "shell"},
    # cli auth: key present in env must NOT be wired into providers.json.
    "claude_cli": {"CLK_PROVIDER": "claude", "CLK_AUTH_MODE": "cli",
                   "ANTHROPIC_API_KEY": "sk-ant-unused"},
    "claude_apikey": {"CLK_PROVIDER": "claude", "CLK_AUTH_MODE": "apikey",
                      "ANTHROPIC_API_KEY": "sk-ant-golden"},
    "claude_apikey_missing_key": {"CLK_PROVIDER": "claude", "CLK_AUTH_MODE": "apikey"},
    "codex_apikey": {"CLK_PROVIDER": "codex", "CLK_AUTH_MODE": "apikey",
                     "OPENAI_API_KEY": "sk-oai-golden"},
    "gemini_apikey_gemini_key": {"CLK_PROVIDER": "gemini", "CLK_AUTH_MODE": "apikey",
                                 "GEMINI_API_KEY": "gm-golden", "GOOGLE_API_KEY": "gg-golden"},
    "gemini_apikey_google_fallback": {"CLK_PROVIDER": "gemini", "CLK_AUTH_MODE": "apikey",
                                      "GOOGLE_API_KEY": "gg-golden"},
    "gemini_cli": {"CLK_PROVIDER": "gemini"},
    # ${CLK_AUTH_MODE:-cli}: empty collapses to cli.
    "auth_mode_empty_defaults_cli": {"CLK_PROVIDER": "claude", "CLK_AUTH_MODE": "",
                                     "ANTHROPIC_API_KEY": "sk-ant-unused"},
    "ollama_defaults": {"CLK_PROVIDER": "ollama"},
    "ollama_custom": {"CLK_PROVIDER": "ollama",
                      "CLK_OLLAMA_ENDPOINT": "http://host.docker.internal:11434",
                      "CLK_OLLAMA_MODEL": "qwen2.5-coder"},
    "openwebui_full": {"CLK_PROVIDER": "openwebui",
                       "CLK_OPENWEBUI_ENDPOINT": "http://localhost:8080",
                       "CLK_OPENWEBUI_API_KEY": "owui-golden",
                       "CLK_OPENWEBUI_MODEL": "llama3.1"},
    "openwebui_blank": {"CLK_PROVIDER": "openwebui"},
    # pi values are stripped; key_type is lowercased.
    "pi_full": {"CLK_PROVIDER": "pi", "CLK_PI_MODEL": " openrouter/free ",
                "CLK_PI_API_KEY": " pi-golden ", "CLK_PI_KEY_TYPE": " OpenRouter "},
    "pi_blank": {"CLK_PROVIDER": "pi"},
}


# ---------------------------------------------------------------------------
# Golden-file parity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", sorted(CONFIG_CASES))
def test_config_env_overrides_match_shell_heredoc(tmp_path: Path, case: str) -> None:
    cfg_path = tmp_path / "clk.config.json"
    shutil.copy(GOLDEN / "base_clk_config.json", cfg_path)
    apply_config_env_overrides(cfg_path, env=CONFIG_CASES[case])
    expected = (GOLDEN / f"config_{case}.json").read_text(encoding="utf-8")
    assert cfg_path.read_text(encoding="utf-8") == expected


@pytest.mark.parametrize("case", sorted(PROVIDER_CASES))
def test_provider_activation_matches_shell_heredoc(tmp_path: Path, case: str) -> None:
    prov_path = tmp_path / "providers.json"
    shutil.copy(GOLDEN / "base_providers.json", prov_path)
    activate_provider(prov_path, env=PROVIDER_CASES[case])
    expected = (GOLDEN / f"providers_{case}.json").read_text(encoding="utf-8")
    assert prov_path.read_text(encoding="utf-8") == expected


def test_config_overrides_noop_when_file_missing(tmp_path: Path) -> None:
    """`if not p.exists(): raise SystemExit(0)` in the heredoc == no-op."""
    missing = tmp_path / "clk.config.json"
    apply_config_env_overrides(missing, env=CONFIG_CASES["full_valid"])
    assert not missing.exists()


def test_config_overrides_preserve_unrelated_keys(tmp_path: Path) -> None:
    cfg_path = tmp_path / "clk.config.json"
    cfg_path.write_text(json.dumps({"custom": {"x": 1}, "robustness": {"keep": True}}),
                        encoding="utf-8")
    apply_config_env_overrides(cfg_path, env={"CLK_ROBUSTNESS_MAX_QA_DEPTH": "5"})
    out = json.loads(cfg_path.read_text(encoding="utf-8"))
    assert out["custom"] == {"x": 1}
    assert out["robustness"] == {"keep": True, "max_qa_depth": 5}


# ---------------------------------------------------------------------------
# Cast helpers (the heredoc's _bool/_csv semantics)
# ---------------------------------------------------------------------------


def test_bool_cast_semantics() -> None:
    for truthy in ("1", "true", "TRUE", " Yes ", "y", "on", "ON"):
        assert _bool(truthy) is True, truthy
    for falsy in ("0", "false", "no", "n", "off", "", "garbage", "2"):
        assert _bool(falsy) is False, falsy


def test_csv_cast_semantics() -> None:
    assert _csv("  a , ,b ,,c  ") == ["a", "b", "c"]
    assert _csv("solo") == ["solo"]
    assert _csv(" , ,, ") == []
    assert _csv("") == []


# ---------------------------------------------------------------------------
# Config validation (port of _clk_missing)
# ---------------------------------------------------------------------------


def _cfg(**over: str) -> dict:
    base = {"CLK_PROVIDER": "shell", "CLK_MAX_ITERATIONS": "10",
            "CLK_PROJECT_NAME": "clk-app", "CLK_RUN_INSTALL": "false",
            "CLK_NO_TUI": "false", "CLK_AUTH_MODE": "cli"}
    base.update(over)
    return base


def test_missing_config_ok_for_shell() -> None:
    assert kickoff._missing_config(_cfg(), {}, "an idea") == []


def test_missing_config_claude_apikey_requires_key() -> None:
    problems = kickoff._missing_config(
        _cfg(CLK_PROVIDER="claude", CLK_AUTH_MODE="apikey"), {}, "idea")
    assert any("ANTHROPIC_API_KEY" in p for p in problems)
    assert kickoff._missing_config(
        _cfg(CLK_PROVIDER="claude", CLK_AUTH_MODE="apikey"),
        {"ANTHROPIC_API_KEY": "sk"}, "idea") == []
    # cli auth mode never requires the key.
    assert kickoff._missing_config(_cfg(CLK_PROVIDER="claude"), {}, "idea") == []


def test_missing_config_gemini_accepts_google_key() -> None:
    cfg = _cfg(CLK_PROVIDER="gemini", CLK_AUTH_MODE="apikey")
    assert kickoff._missing_config(cfg, {"GOOGLE_API_KEY": "g"}, "idea") == []
    assert kickoff._missing_config(cfg, {}, "idea")


def test_missing_config_openwebui_requires_endpoint_and_model() -> None:
    problems = kickoff._missing_config(_cfg(CLK_PROVIDER="openwebui"), {}, "idea")
    assert any("CLK_OPENWEBUI_ENDPOINT" in p for p in problems)
    assert any("CLK_OPENWEBUI_MODEL" in p for p in problems)


def test_missing_config_rejects_unknown_provider_and_bad_iterations() -> None:
    problems = kickoff._missing_config(
        _cfg(CLK_PROVIDER="hal9000", CLK_MAX_ITERATIONS="lots"), {}, "idea")
    assert any("not recognised" in p for p in problems)
    assert any("CLK_MAX_ITERATIONS" in p for p in problems)


def test_missing_config_no_tui_requires_idea() -> None:
    problems = kickoff._missing_config(_cfg(CLK_NO_TUI="true"), {}, "")
    assert any("idea argument is required" in p for p in problems)
    assert kickoff._missing_config(_cfg(CLK_NO_TUI="true"), {}, "an idea") == []


# ---------------------------------------------------------------------------
# CLI flag surface + early-exit modes (--list / --clean / --restore)
# ---------------------------------------------------------------------------


def _parse(*argv: str) -> argparse.Namespace:
    return build_parser().parse_args(["kickoff", *argv])


def test_parser_mirrors_kickoff_sh_flags() -> None:
    ns = _parse("--setup", "--restore", "--list", "--clean", "7d",
                "--provider", "shell", "--max-iterations", "3",
                "--project-name", "p", "--no-tui", "--run-install", "my idea")
    assert ns.setup and ns.restore and ns.list_mode
    assert ns.clean == "7d"
    assert ns.provider == "shell"
    assert ns.max_iterations == "3"
    assert ns.project_name == "p"
    assert ns.no_tui_override == "true"
    assert ns.run_install is True
    assert ns.idea == "my idea"
    assert ns.func is kickoff.cmd_kickoff


def test_parser_tui_flag_wins_when_last() -> None:
    assert _parse("--no-tui", "--tui").no_tui_override == "false"
    assert _parse("--tui", "--no-tui").no_tui_override == "true"
    assert _parse().no_tui_override is None


def test_list_without_workspace(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    assert kickoff.cmd_kickoff(_parse("--list")) == 0
    assert "no workspace" in capsys.readouterr().out.lower()


def test_list_shows_kickoff_dirs(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "workspace" / "kickoff-20260101-120000").mkdir(parents=True)
    state = tmp_path / "workspace" / "kickoff-20260201-120000" / ".clk" / "state"
    state.mkdir(parents=True)
    (state / "idea.json").write_text(json.dumps({"title": "A grand idea"}), encoding="utf-8")
    assert kickoff.cmd_kickoff(_parse("--list")) == 0
    out = capsys.readouterr().out
    assert "kickoff-20260101-120000" in out
    assert "kickoff-20260201-120000" in out
    assert "A grand idea" in out


def test_clean_rejects_unparseable_duration(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "workspace" / "kickoff-x").mkdir(parents=True)
    assert kickoff.cmd_kickoff(_parse("--clean", "garbage")) == 2
    assert "--clean expects" in capsys.readouterr().err


def test_clean_without_workspace(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    assert kickoff.cmd_kickoff(_parse("--clean", "7d")) == 0
    assert "nothing to clean" in capsys.readouterr().out.lower()


def test_clean_nothing_old_enough(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "workspace" / "kickoff-fresh").mkdir(parents=True)
    assert kickoff.cmd_kickoff(_parse("--clean", "7d")) == 0
    assert "no kickoff dirs older" in capsys.readouterr().out.lower()


def test_clean_refuses_without_tty(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    stale = tmp_path / "workspace" / "kickoff-stale"
    stale.mkdir(parents=True)
    old = time.time() - 8 * 86400
    os.utime(stale, (old, old))
    monkeypatch.setattr(kickoff, "_open_tty", lambda: None)
    assert kickoff.cmd_kickoff(_parse("--clean", "7d")) == 2
    captured = capsys.readouterr()
    assert "non-interactive" in (captured.out + captured.err).lower()
    assert stale.exists()


def test_restore_swaps_env_bak_back(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(kickoff, "harness_root", lambda: tmp_path)
    (tmp_path / ".env.bak").write_text("KEY=from-bak\n", encoding="utf-8")
    assert kickoff.cmd_kickoff(_parse("--restore")) == 0
    assert (tmp_path / ".env").read_text(encoding="utf-8") == "KEY=from-bak\n"
    assert not (tmp_path / ".env.bak").exists()


def test_restore_without_bak_fails_cleanly(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.setattr(kickoff, "harness_root", lambda: tmp_path)
    assert kickoff.cmd_kickoff(_parse("--restore")) == 1
    assert "no" in capsys.readouterr().err.lower()


def test_missing_config_exits_2_without_tty(tmp_path: Path, monkeypatch, capsys) -> None:
    """A non-interactive run with invalid config prints the problems and
    exits 2 instead of creating a kickoff dir."""
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(kickoff, "harness_root", lambda: tmp_path)  # no .env here
    monkeypatch.setattr(kickoff, "_open_tty", lambda: None)
    monkeypatch.delenv("CLK_PROVIDER", raising=False)
    rc = kickoff.cmd_kickoff(_parse("--provider", "hal9000", "--no-tui", "idea"))
    assert rc == 2
    err = capsys.readouterr().err
    assert "missing or invalid configuration" in err
    assert "not recognised" in err
    assert not (tmp_path / "workspace").exists()
